@extends('layouts.admin')

@section('contents')
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Profile</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-sm-12">
                <form action="{{ url('admin/user/profile') }}" method="post">
                    {!! csrf_field() !!}
                    <div>
                        <input type="checkbox" name="enable_google2fa" value="1" @if($url) checked @endif> Enable Google Two Factor Authentication
                    </div>
                    @if($url)
                    <div>
                        <img src="{{ $url }}" alt="">
                        <p>
                            Enabling two factor authentication increases security of your account.
                            You will need to download Google Authenticator or a similar app on to your mobile device.
                            When you login you will be asked to provide a token generated by the app.
                        </p>
                    </div>
                    @endif
                    <div>
                        <input type="submit" class="btn btn-info" value="保存">
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                @if(!$github)
                <a href="{{ url('admin/github/redirect') }}">Github 授权</a>
                @endif
            </div>
        </div>
    </div>
@endsection
